### PR TITLE
Add support for more results per page

### PR DESCRIPTION
**Pull request by ZeroDragon**
Allows opts to have a `maxResults` key to change the number of items displayed into a single page
```js
const opts = {
  /* required */
  list: [ 'whale', 'giraffe', 'monkey' ],

  /* optional (and defaults) */
  // filtering mode (user can change modes by pressing ctrl-s)
  mode: 'fuzzy' || 'normal',

  // prefill user input
  prefill: '',

  // desired quantity of results per page (defaults to 6)
  maxResults: 6,

  // text before each displayed line, list index supplied as arg
  prelinehook: function ( index ) { return '' },

  // text after each displayed line, list index supplied as arg
  postlinehook: function ( index ) { return '' }
}
```

Example with 30 results per page
image

tested with 1500 items in memory and adds no lag at all
Also it does not break compatibility since by default falls back to previous behaviour.
image

### CODE REVIEW

**Comment by talmobi** [comment]
@ZeroDragon hello -- thanks for your PR

I refactored it to use "height" option and "--height" cli argument where you set percentage of how much of the screen should be used to display results. This is similar to how the original fzf does it ( https://github.com/junegunn/fzf/blob/master/ADVANCED.md#--height )

For your case it would probably be `height: 100` (or `--height 100`) so that 100% available screen space is used to display the list of results.

I have not released it on npm but it is pushed to github master branch -- can you try it out and see if it works for you? thank you

**Comment by talmobi** [comment]
@ZeroDragon hello -- does the addition of `--height` cli arg and `height` option solve your use case? thanks~

**Comment by ZeroDragon** [comment]
Looks like its the same as my PR, thanks for adding that `height` option. 
Keep up the good work!

**Comment by talmobi** [comment]
@ZeroDragon <3 version 0.12.0 has been published to npm that includes this feature (along with --keep-right cli arg and `<c-e>` to toggle --keep-right)

**Pull request merged**
